words <- c(
  "When things go wrong",
  "and will not come right,",
  "Though you do the best",
  "you can, When life looks",
  "black as the hour of night",
  "A pint of plain is your only",
  "man. When money’s tight",
  "and hard to get, And your",
  "horse has also ran, When",
  "all you have is a heap of debt",
  "A pint of plain is your only man",
  "When health is bad and your heart",
  "feels strange, And your face is",
  "pale and wan, When doctors say",
  "you need a change–A pint of plain",
  "is your only man. When food is scarce",
  "and your larder bare, And no rashers",
  "grease your pan, When hunger grows",
  "as your meals are rare–A pint of plain",
  "is your only man. In time of trouble and",
  "lousey strife, You have still got a darlint",
  "plan, You still can turn to a brighter life",
  "A pint of plain is your only man",
  "",
  "The Workman's Friend",
  "")
